# This is a basic workflow to help you get started with Actions

name: Simple Local
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
    run: echo "Hello World!"
